# 1 "data/maps/RustboroCity_Flat1_1F/scripts.pory"

# 2 "data/maps/RustboroCity_Flat1_1F/scripts.pory"
RustboroCity_Flat1_1F_MapScripts::
# 3 "data/maps/RustboroCity_Flat1_1F/scripts.pory"
	.byte 0
# 4 "data/maps/RustboroCity_Flat1_1F/scripts.pory"

# 5 "data/maps/RustboroCity_Flat1_1F/scripts.pory"
RustboroCity_Flat1_1F_EventScript_Man::
# 6 "data/maps/RustboroCity_Flat1_1F/scripts.pory"
	msgbox RustboroCity_Flat1_1F_Text_Man, MSGBOX_NPC
# 7 "data/maps/RustboroCity_Flat1_1F/scripts.pory"
	end
# 8 "data/maps/RustboroCity_Flat1_1F/scripts.pory"

# 9 "data/maps/RustboroCity_Flat1_1F/scripts.pory"
RustboroCity_Flat1_1F_EventScript_Woman::
# 10 "data/maps/RustboroCity_Flat1_1F/scripts.pory"
	msgbox RustboroCity_Flat1_1F_Text_Woman, MSGBOX_NPC
# 11 "data/maps/RustboroCity_Flat1_1F/scripts.pory"
	end
# 12 "data/maps/RustboroCity_Flat1_1F/scripts.pory"

# 13 "data/maps/RustboroCity_Flat1_1F/scripts.pory"
RustboroCity_Flat1_1F_Text_Man: @ 82150E0
# 14 "data/maps/RustboroCity_Flat1_1F/scripts.pory"
	.string "What's for dinner today?\n"
# 15 "data/maps/RustboroCity_Flat1_1F/scripts.pory"
	.string "My specialty, Seaweed Stew!$"
# 16 "data/maps/RustboroCity_Flat1_1F/scripts.pory"

# 17 "data/maps/RustboroCity_Flat1_1F/scripts.pory"
RustboroCity_Flat1_1F_Text_Woman: @ 8215115
# 18 "data/maps/RustboroCity_Flat1_1F/scripts.pory"
	.string "My husband likes to cook.\p"
# 19 "data/maps/RustboroCity_Flat1_1F/scripts.pory"
	.string "I don't dare to tell him the truth.$"
