# 1 "data/maps/RustboroCity_House2/scripts.pory"

# 2 "data/maps/RustboroCity_House2/scripts.pory"
RustboroCity_House2_MapScripts::
# 3 "data/maps/RustboroCity_House2/scripts.pory"
	.byte 0
# 4 "data/maps/RustboroCity_House2/scripts.pory"

# 5 "data/maps/RustboroCity_House2/scripts.pory"
@ new:
# 6 "data/maps/RustboroCity_House2/scripts.pory"

# 7 "data/maps/RustboroCity_House2/scripts.pory"
RustboroCity_House2_EventScript_LittleGirl:: @ 8215EBD
# 8 "data/maps/RustboroCity_House2/scripts.pory"
	msgbox RustboroCity_House2_Text_Nintendo64, MSGBOX_NPC
# 9 "data/maps/RustboroCity_House2/scripts.pory"
	end
# 10 "data/maps/RustboroCity_House2/scripts.pory"

# 11 "data/maps/RustboroCity_House2/scripts.pory"
RustboroCity_House2_Text_Nintendo64: @ 8215F21
# 12 "data/maps/RustboroCity_House2/scripts.pory"
	.string "Check this out!\p"
# 13 "data/maps/RustboroCity_House2/scripts.pory"
	.string "I found my dad's old video\n"
# 14 "data/maps/RustboroCity_House2/scripts.pory"
	.string "game console!$"
# 15 "data/maps/RustboroCity_House2/scripts.pory"

# 16 "data/maps/RustboroCity_House2/scripts.pory"
@ old:
# 17 "data/maps/RustboroCity_House2/scripts.pory"

# 18 "data/maps/RustboroCity_House2/scripts.pory"
RustboroCity_House2_EventScript_PokefanF::
# 19 "data/maps/RustboroCity_House2/scripts.pory"
	msgbox RustboroCity_House2_Text_TrainerSchoolExcellent, MSGBOX_NPC
# 20 "data/maps/RustboroCity_House2/scripts.pory"
	end
# 21 "data/maps/RustboroCity_House2/scripts.pory"

# 22 "data/maps/RustboroCity_House2/scripts.pory"
//RustboroCity_House2_EventScript_LittleGirl::
# 23 "data/maps/RustboroCity_House2/scripts.pory"
	//msgbox RustboroCity_House2_Text_RoxanneKnowsALot, MSGBOX_NPC
# 24 "data/maps/RustboroCity_House2/scripts.pory"
	//end
# 25 "data/maps/RustboroCity_House2/scripts.pory"

# 26 "data/maps/RustboroCity_House2/scripts.pory"
RustboroCity_House2_Text_TrainerSchoolExcellent:
# 27 "data/maps/RustboroCity_House2/scripts.pory"
	.string "The TRAINER'S SCHOOL is excellent.\p"
# 28 "data/maps/RustboroCity_House2/scripts.pory"
	.string "If you study there, you could even\n"
# 29 "data/maps/RustboroCity_House2/scripts.pory"
	.string "become a GYM LEADER.$"
# 30 "data/maps/RustboroCity_House2/scripts.pory"

# 31 "data/maps/RustboroCity_House2/scripts.pory"
RustboroCity_House2_Text_RoxanneKnowsALot:
# 32 "data/maps/RustboroCity_House2/scripts.pory"
	.string "ROXANNE, the GYM LEADER, really knows\n"
# 33 "data/maps/RustboroCity_House2/scripts.pory"
	.string "a lot about POKéMON.\p"
# 34 "data/maps/RustboroCity_House2/scripts.pory"
	.string "She's really strong, too!$"
